package _training;

public class Functions {
    static void printHi() {
        System.out.println("Hello!");
        System.out.println("lksa;jdfas;k");
        System.out.println("fasoiudhaoiuf");
    }

    public static void main(String[] args) {
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
        printHi();
    }
}
