package _training;

public class MathProblems {

    public static void main(String[] args) {
        int mynumberone = 1;
        int mynumbertwo = 950;
        int mynumberthree = mynumberone + mynumbertwo;
        System.out.println( mynumberthree);
        System.out.println("this is showing "+mynumberone +" being added to " +mynumbertwo +" in this equation");
        float mynumberfour = 5.6f;
        float mynumberfive = 8.7f;
        float mynumbersix = mynumberfour + mynumberfive;
        System.out.println(mynumbersix);
        System.out.println("this is showing "+mynumberfour +" being added to " +mynumberfive +" in this equation");
        double mynumberdoone = 5.8f;
        double mynumberdotwo = 96.7f;
        double mynumberdothree = mynumberdoone + mynumberdotwo;
        System.out.println(mynumberdothree);
        System.out.println("this is showing "+mynumberdoone +" being added to " +mynumberdotwo +" in this equation");
        int lukenumone = 5;
        int lukenumtwo = 8;
        int lukenumthree = lukenumone + lukenumtwo;
        System.out.println(lukenumthree);
        System.out.println("this is showing "+lukenumone +" being added to " +lukenumtwo +" in this equation");
        int mynumbersubone = 359;
        int mynumbersubtwo = 943;
        int mynumbersubthree = mynumbersubone - mynumbersubtwo;
        System.out.println( mynumbersubthree);
        System.out.println("this is showing "+mynumbersubone +" being subtracted from to " +mynumbersubtwo +" in this equation");
        float mynumbersubfour = 97.7f;
        float mynumbersubfive = 94.9f;
        float mynumbersubsix = mynumbersubfour - mynumbersubfive;
        System.out.println(mynumbersubsix);
        System.out.println("this is showing "+mynumbersubfour +" being subtracted from to " +mynumbersubfive +" in this equation");
        double mynumbersubedone = 83.8;
        double mynumbersubedtwo = 96.7;
        double mynumbersubedthree = mynumbersubedone - mynumbersubedtwo;
        System.out.println(mynumbersubedthree);
        System.out.println("this is showing "+mynumbersubedone +" being subtracted from to " +mynumbersubedtwo +" in this equation");
        int catsrebelion = 5;
        int catsrebeliontwo = 21;
        int catsrebelionthree = catsrebelion - catsrebeliontwo;
        System.out.println(catsrebelionthree);
        System.out.println("this is showing "+catsrebelion +" being subtracted from to " +catsrebeliontwo +" in this equation");
        int mynumbermione = 16;
        int mynumbermitwo = 4;
        int mynumbermithree = mynumbermione * mynumbermitwo;
        System.out.println( mynumbermithree);
        System.out.println("this is showing "+mynumbermione +" being multiplyed to " +mynumbersubtwo +" in this equation");
        float mynumbermifour = 5.6f;
        float mynumbermifive = 8.7f;
        float mynumbermisix = mynumbermifour * mynumbermifive;
        System.out.println(mynumbermisix);
        System.out.println("this is showing "+mynumbermifour +" being multiplyed to " +mynumbermifive +" in this equation");
        double mynumbermiione = 93.7;
        double mynumbermiitwo = 38.9;
        double mynumbermiithree = mynumbermiione * mynumbermiitwo;
        System.out.println(mynumbermiithree);
        System.out.println("this is showing "+mynumbermiione +" being multiplyed to " +mynumbermiitwo +" in this equation");
        int millionstreams = 1000000;
        int millionstreamson = 1000;
        int millionstreamsonspotify = millionstreams * millionstreamson;
        System.out.println(millionstreamsonspotify);
        System.out.println("this is showing "+millionstreams +" being multiplyed to " +millionstreamson +" in this equation");
        int mynumberdivone = 1;
        int mynumberdivtwo = 950;
        int mynumberdivthree = mynumberdivone / mynumberdivtwo;
        System.out.println( mynumberdivthree);
        System.out.println( "this is showsing "+mynumberdivone +" being divided by " +mynumberdivtwo);
        float mynumberdivfour = 5.6f;
        float mynumberdivfive = 8.7f;
        float mynumberdivsix = mynumberdivfour / mynumberdivfive;
        System.out.println(mynumberdivsix);
        System.out.println( "this is showing "+mynumberdivfour +" being divided by " +mynumberdivfive);
        double mynumberdivvone = 5.8;
        double mynumberdivvtwo = 96.7;
        double mynumberdivvthree = mynumberdivvone / mynumberdivvtwo;
        System.out.println(mynumberdivvthree);
        System.out.println( "this is showing "+mynumberdivvone +" being divided by" +mynumberdivvtwo);
        int applecircle = 99900000;
        int applecircletwo = 99;
        int appletoexpencive = applecircle / applecircletwo;
        System.out.println(appletoexpencive);
        System.out.println( "this is showing "+applecircle +" being divided by" +applecircletwo);

    }
}
