package _training;

public class Variables {
    public static void main(String[] args) {
        int myNum = 1;
        int myOtherNum = 2;
        int myOthernum2 = 3;
        int myothernum3 = 1;
        int myothernum4 = 2;
        int myothernum5 = 35;
        int myothernum6 = 109;
        int myothernum7 = 7;
        int myothernum8 = 3;
        int myothernum9 = 72;
        int myothernum10 = 10;
        int myothernum11 = 92;
        int myothernum12 = 35;
        int myothernum13 = 729;
        int myothernum14 = 4;
        int myothernum15 = 5;
        int myothernum16 = 892;
        int myothernum17 = 39;
        int myothernum18 = 10;
        String mytext = "Hello!";
        String mytext2 = " Again!";
        float mydecimal = 2.5f;
        float myotherdecimal = 5.0f;
        float itsadecimal = 1.5f;
        float itsadecimal2 = 3.0f;
        float itsadecimal3 = 6.4f;
        float itsadecimal4 = 1.7f;
        float itsadecimal5 = 40.6f;
        float itsadecimal6 = 177.7f;
        float itsadecimal7 = 783.93f;
        float itsadecimal8 = 300.722f;
        double mydoubledecimal = 6.7;
        double mydoubledecimal2 = 4.1;
        double itsadoubledecimal = 9.3;
        double itsadoubledecimal2 = 3.7;
        double itsadoubledecimal3 = 10.3;
        double itsadoubledecimal4 = 11.7;
        double itsadoubledecimal5 = 0.23;
        double itsadoubledecimal6 = 19.7;
        double itsadoubledecimal7 = 0.7832;
        double itsadoubledecimal8 = 1009.4;
        boolean ateBreakfast = true;
        boolean ateLunch = true;
        boolean ateDinner = false;
        // Get the sum of the two numbers
        int myFinalNum = myNum + myOtherNum;
        int myFinalNum2 = myFinalNum * myOthernum2;
        int myFinalNum3 = myothernum3 + myothernum4;
        int myFinalNum4 = myothernum5 + myothernum6; 
        int myFinalNum5 = myothernum7 - myothernum8;
        int myFinalNum6 = myothernum9 - myothernum10;
        int myFinalNum7 = myothernum11 * myothernum12;
        int myFinalNum8 = myothernum13 * myothernum14;
        int myFinalNum9 = myothernum15 / myothernum16;
        int myFinalNum10 = myothernum17 / myothernum18;
        float Mylastdecimal = mydecimal / myotherdecimal;
        float itsalastdecimal = itsadecimal + itsadecimal2;
        float itsalastdecimal2 = itsadecimal3 - itsadecimal4;
        float itsalastdecimal3 = itsadecimal5 * itsadecimal6;
        float itsalastdecimal4 = itsadecimal7 / itsadecimal8;
        double myfinaldoublelastdecimal = mydoubledecimal / mydoubledecimal2;
        double itsadoublelastdecimal = itsadoubledecimal + itsadoubledecimal2;
        double itsadoublelastdecimal2 = itsadoubledecimal3 - itsadoubledecimal4;
        double itsadoublelastdecimal3 = itsadoubledecimal5 * itsadoubledecimal6;
        double itsadoublelastdecimal4 = itsadoubledecimal7 / itsadoubledecimal8;
        String myfinaltext = mytext + mytext2;
        System.out.println(myFinalNum2);
        System.out.println(myfinaltext);
        System.out.println(Mylastdecimal);
        System.out.println(myfinaldoublelastdecimal);
        System.out.println(ateBreakfast && ateLunch);
        System.out.println(ateLunch && ateDinner);
        System.out.println(myFinalNum3);
        System.out.println(itsalastdecimal);
        System.out.println(itsadoublelastdecimal);
        System.out.println(myFinalNum4);
        System.out.println(myFinalNum5);
        System.out.println(myFinalNum6);
        System.out.println(itsalastdecimal2);
        System.out.println(itsadoublelastdecimal2);
        System.out.println(myFinalNum7);
        System.out.println(myFinalNum8);
        System.out.println(itsalastdecimal3);
        System.out.println(itsadoublelastdecimal3);
        System.out.println(myFinalNum9);
        System.out.println(myFinalNum10);
        System.out.println(itsalastdecimal4);
        System.out.println(itsadoublelastdecimal4);
    }
}
